python decode_seq2seq.py \
  --model_type unilm  \
  --model_name_or_path "./data/model/"  \
  --model_recover_path "./output/model.bin"  \
  --max_seq_length 512  \
  --input_file "./data/test_data.json"  \
  --output_file "./output/predict_.json"  \
  --do_lower_case  \
  --batch_size 32 \
  --beam_size 5  \
  --max_tgt_length 128